[package]
name = "solsnype-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.0"
solana-sdk = "2.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
solana-account-decoder = "2.2.0"
dotenv = "0.15.0"
bs58 = "0.5.1"
